name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew release

      
    - name: Upload GitHub Actions artifact of vcpkg build
      uses: actions/upload-artifact@v3
      with:
        name: scene-dev
        path: ${{ github.workspace }}/app/build/outputs/apk/release/*.apk
